### ISSUE TITLE
The animated enigma logo doesn't reappear once someone returns from the menu.

### ISSUE THREAD

**Issue by partha2000** [EnigmaVSSUT/EnigmaNewWebsite#9]
### Steps to reproduce:
1. Load the website
2. The Enigma logo appears.
3. Go to the menu.
4. Return from the menu.
5. The logo doesn't reload.

#### If you are sending a pull request then mention that you are solving this issue.

**Comment by ashuvssut** [comment]
I want to work on this issue #9. Can I get this assigned to me?

**Comment by PseudoNerd** [comment]
Sure, @ashuvssut take it away.
